version: "3.6"
services:
  haproxy:
    image: via/haproxy:2.5.1-alpine
    ports:
      - 15672:15672
      - 5672:5672
      - 1936:1936
    networks:
      - prod
    deploy:
      mode: global
networks:
  prod:
    external: true
